import { Store, Stethoscope, Utensils, Fuel, CreditCard, Phone, Router } from 'lucide-react';

export const CLIENTES_MOCK = [
  {
    id: '1',
    name: 'Farmacia Central',
    address: 'Av. Principal 123',
    status: 'warning',
    statusText: 'PROX. VENCIMIENTO',
    Icon: Stethoscope,
  },
  {
    id: '2',
    name: 'Tienda Don Juan',
    address: 'Calle Luna 45',
    status: 'danger',
    statusText: 'VENCIDO',
    Icon: Store,
  },
  {
    id: '3',
    name: 'Restaurante El Faro',
    address: 'Malecón Sur KM 4',
    status: 'success',
    statusText: 'AL DÍA',
    Icon: Utensils,
  },
  {
    id: '4',
    name: 'Estación de Servicio',
    address: 'Ruta 5, KM 120',
    status: 'warning',
    statusText: 'PROX. VENCIMIENTO',
    Icon: Fuel,
  },
  {
    id: '5',
    name: 'Supermercado Sol',
    address: 'Calle 10, Nro 456',
    status: 'inactive',
    statusText: 'DESACTIVADO',
    Icon: Store,
  },
  {
    id: '6',
    name: 'Clínica del Sur',
    address: 'Av. Santa Fe 2345',
    status: 'danger',
    statusText: 'VENCIDO',
    Icon: Stethoscope,
  },
  {
    id: '7',
    name: 'Panadería Antigua',
    address: 'Pasaje Viejo 78',
    status: 'inactive',
    statusText: 'DESACTIVADO',
    Icon: Utensils,
  },
  {
    id: '8',
    name: 'Ferretería El Tornillo',
    address: 'Av. Libertador 500',
    status: 'success',
    statusText: 'AL DÍA',
    Icon: Store,
  },
  {
    id: '9',
    name: 'Gimnasio FitLife',
    address: 'Calle Fitness 12',
    status: 'warning',
    statusText: 'PROX. VENCIMIENTO',
    Icon: Fuel,
  },
  {
    id: '10',
    name: 'Librería Escolar',
    address: 'Calle Belgrano 34',
    status: 'success',
    statusText: 'AL DÍA',
    Icon: Store,
  },
  {
    id: '11',
    name: 'Carnicería Carlos',
    address: 'Av. San Martín 1200',
    status: 'danger',
    statusText: 'VENCIDO',
    Icon: Utensils,
  },
  {
    id: '12',
    name: 'Pet Shop Luquitas',
    address: 'Av. Rivadavia 890',
    status: 'warning',
    statusText: 'PROX. VENCIMIENTO',
    Icon: Store,
  },
  {
    id: '13',
    name: 'Óptica Visión',
    address: 'Calle Florida 56',
    status: 'success',
    statusText: 'AL DÍA',
    Icon: Stethoscope,
  },
  {
    id: '14',
    name: 'Pizzería Napo',
    address: 'Av. Corrientes 4500',
    status: 'inactive',
    statusText: 'DESACTIVADO',
    Icon: Utensils,
  },
  {
    id: '15',
    name: 'Kiosco Las Horas',
    address: 'Calle 25 de Mayo 102',
    status: 'warning',
    statusText: 'PROX. VENCIMIENTO',
    Icon: Store,
  },
  {
    id: '16',
    name: 'Laboratorio Alfa',
    address: 'Av. Pueyrredón 456',
    status: 'danger',
    statusText: 'VENCIDO',
    Icon: Stethoscope,
  },
  {
    id: '17',
    name: 'Cafe del Barrio',
    address: 'Calle Soler 3421',
    status: 'success',
    statusText: 'AL DÍA',
    Icon: Utensils,
  },
  {
    id: '18',
    name: 'Fiambrería Gourmet',
    address: 'Av. Callao 123',
    status: 'inactive',
    statusText: 'DESACTIVADO',
    Icon: Store,
  },
  {
    id: '19',
    name: 'Lavadero de Autos',
    address: 'Calle Brown 90',
    status: 'warning',
    statusText: 'PROX. VENCIMIENTO',
    Icon: Fuel,
  },
  {
    id: '20',
    name: 'Centro de Estética',
    address: 'Calle Junín 889',
    status: 'danger',
    statusText: 'VENCIDO',
    Icon: Stethoscope,
  },
];

export const DEFAULT_INFO_ITEMS = [
  {
    label: 'Plan Mensual',
    subValue: '$12.500 / mes',
    icon: CreditCard,
    special: true,
  },
  {
    label: 'Teléfono',
    value: '+54 11 5555-0192',
    subValue: 'Contacto: Miguel Gómez',
    icon: Phone,
  },
  {
    label: 'Infraestructura',
    value: 'Alquiler  de Post',
    subValue: '3 Terminales instaladas',
    icon: Router,
  },
];

export const CLIENT_FILTER_OPTIONS = [
  { id: 'all', label: 'Todos' },
  { id: 'success', label: 'Al día' },
  { id: 'warning', label: 'Próximo' },
  { id: 'danger', label: 'Vencido' },
  { id: 'inactive', label: 'Inactivos' },
];

export const COBROS_FILTER_OPTIONS = [
  { id: 'all', label: 'Todos' },
  { id: 'success', label: 'Pagados' },
  { id: 'warning', label: 'Pendientes' },
  { id: 'danger', label: 'Rechazados' },
];
